### PR TITLE
Both `--input` and `--url` are optional

### LINKED ISSUE #23: There's no way to run the container on data that was generated
I would like to use the following command line to run the container with pre-processed data:
```
...
entrypoint: ./graphhopper.sh --host 0.0.0.0 -o /data/default-gh/ -c /data/gh-config.yml
...
```

This will currently fail with: `No file or url were specified.`
Basically the test needs to be better defined by checking file and graph settings, and maybe action? IDK...

There's currently a workaround of setting an non-existing input file.

### PR DESCRIPTION
**Pull request by zstadler**
They remain mutually exclusive.

Update and clarify the help text.

Resolves #23

### CODE REVIEW

File: graphhopper.sh [hunk 1]
```diff
@@ -78,12 +77,6 @@ if [ "$URL" != "" ]; then
   FILE="data.pbf"
 fi
 
-if [ "$FILE" = "" ]; then
```
Comment (HarelM) [inline graphhopper.sh:81]: How will removing this affect the lines below for the dirname and GH java command-line?

Comment (zstadler) [reply graphhopper.sh:81]: You are absolutely right!
I believe the code cleanup addresses this.

File: Dockerfile [hunk 2]
```diff
@@ -18,9 +18,11 @@ COPY --from=build /graphhopper/web/target/graphhopper*.jar .
 
 COPY graphhopper.sh graphhopper/config-example.yml .
 
+RUN sed -i '/^ *bind_host/s/^ */&# /p' config-example.yml
```
Comment (HarelM) [inline Dockerfile:21]: I think I understand why this is here, but a comment detailing why would be better, I think.

File: Dockerfile [hunk 3]
```diff
@@ -18,9 +18,11 @@ COPY --from=build /graphhopper/web/target/graphhopper*.jar .
...
+
 VOLUME [ "/data" ]
 
-EXPOSE 8989
+EXPOSE 8989 8990
```
Comment (HarelM) [inline Dockerfile:25]: Is 8990 actually needed from the outside?

File: graphhopper.sh [hunk 4]
```diff
@@ -55,49 +54,21 @@ while [ ! -z $1 ]; do
...
 if [ "$URL" != "" ]; then
-  wget -S -nv -O "data.pbf" "$URL"
-  FILE="data.pbf"
-fi
-
-if [ "$FILE" = "" ]; then
-  echo -e "No file or url were specified."
-  printBashUsage
-  exit 2
+  wget -S -nv -O "${FILE:=data.pbf}" "$URL"
```
Comment (HarelM) [inline graphhopper.sh:65]: This is not initialized above since it can stay empty?

File: Dockerfile (hunk 3 above)
Comment (zstadler) [reply Dockerfile:25]: This only enables mapping the port with docker or docker-compose.

File: graphhopper.sh (hunk 4 above)
Comment (zstadler) [reply graphhopper.sh:65]: - It is not initialized above
- It can stay empty if graphhopper is using an existing graph-cache, as described in [my "expansion" comment](https://github.com/IsraelHikingMap/graphhopper-docker-image-push/issues/23#issuecomment-1321193643)

**Review by HarelM — APPROVED** [review]
